export const cardData = [
  {
    id: 1,
    city: "New York",
    location: "Equinox Hudson Yards",
    phone: "123-456-7890",
    imgSrc: "https://framerusercontent.com/images/W1L5fI4RpqurtydbmGY5crv0ItM.jpg?scale-down-to=512",
    address: "500 W 33rd St, New York, NY 10001, USA",
  },
  {
    id: 2,
    city: "Los Angeles",
    location: "Gold's Gym Venice",
    phone: "987-654-3210",
    imgSrc: "https://framerusercontent.com/images/LsEJrnNgbBAk08pLHwNcDRF4oLo.jpeg?scale-down-to=512",
    address: "360 Hampton Dr, Venice, CA 90291, USA",
  },
  {
    id: 3,
    city: "Chicago",
    location: "East Bank Club",
    phone: "555-555-5555",
    imgSrc: "https://framerusercontent.com/images/LMf0H8b1MNKO0RwpkoYqfCtUaOg.jpeg?scale-down-to=512",
    address: "500 N Kingsbury St, Chicago, IL 60654, USA",
  },
  {
    id: 4,
    city: "San Francisco",
    location: "Fitness SF - SOMA",
    phone: "321-654-0987",
    imgSrc: "https://framerusercontent.com/images/64IsefqJykeOf5kk2ETV1gkGQ.jpg?scale-down-to=512",
    address: "1001 Brannan St, San Francisco, CA 94103, USA",
  },
  {
    id: 5,
    city: "Seattle",
    location: "Seattle Athletic Club Downtown",
    phone: "444-555-6666",
    imgSrc: "https://framerusercontent.com/images/64IsefqJykeOf5kk2ETV1gkGQ.jpg?scale-down-to=512",
    address: "2020 Western Ave, Seattle, WA 98121, USA",
  },
  {
    id: 6,
    city: "Las Vegas",
    location: "City Athletic Club",
    phone: "888-777-9999",
    imgSrc: "https://framerusercontent.com/images/PGAbUTA6vfEEZzEnxTdQDESoOU.png?scale-down-to=512",
    address: "7980 W Sahara Ave, Las Vegas, NV 89117, USA",
  },
  {
    id: 7,
    city: "Miami",
    location: "Anatomy Miami Beach",
    phone: "222-333-4444",
    imgSrc: "https://framerusercontent.com/images/DOzktr1SJvtZ2JWlN1robGanA.jpg?scale-down-to=512",
    address: "1220 20th St, Miami Beach, FL 33139, USA",
  },
  {
    id: 8,
    city: "Boston",
    location: "Equinox Dartmouth",
    phone: "111-222-3333",
    imgSrc: "https://framerusercontent.com/images/HJRDzDi84uefoHHZYsokhFiak.png?scale-down-to=512",
    address: "131 Dartmouth St, Boston, MA 02116, USA",
  }
];
